<?php

/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Darcy Clarke. http://themify.me
/*  				Copyright (C) 2010 Themify
/*
/***************************************************************************/

/* 	Setting Modules
/***************************************************************************/
	
	///////////////////////////////////////////
	// Site Logo
	///////////////////////////////////////////
	function themify_site_logo($data=array()){
		if($data['attr']['target'] != ''){
			$target = "<span class='hide target'>".$data['attr']['target']."</span>";	
		}
		$data = get_data();
		if($data['setting-site_logo'] == "image"){
			$image = "checked='checked'";
			$image_display = "style='display:block;'";
			$text_display = "style='display:none;'";
		} else {
			$text = "checked='checked'";	
			$text_display = "style='display:block;'";
			$image_display = "style='display:none;'";
		}
		return '<p>
					<span class="label">Отображать</span> 
						<input name="setting-site_logo" type="radio" value="text" '.$text.' /> Заголовок сайта
						<input name="setting-site_logo" type="radio" value="image" '.$image.' /> Изображение
					</span>
					'.$target.'
					<span class="pushlabel image" '.$image_display.'>
						<input type="text" class="width10" name="setting-site_logo_image_value" value="'.$data['setting-site_logo_image_value'].'" />
					</span>
					<span class="pushlabel image" '.$image_display.'>
						<a href="#" id="setting-'.$data['category'].'-'.$data['title'].'-site_logo" class="upload-btn upload-image logo">+ Загрузить</a>
					</span>
					<span class="pushlabel clear image" '.$image_display.'>
						<input type="text" name="setting-site_logo_width" class="width2" value="'.$data['setting-site_logo_width'].'" /> ширина
						<input type="text" name="setting-site_logo_height" class="width2" value="'.$data['setting-site_logo_height'].'" /> высота
					</span>
				</p>';	
	}
	
	///////////////////////////////////////////
	// Favicon Module
	///////////////////////////////////////////
	function themify_favicon($data=array()){
		if($data['attr']['target'] != ''){
			$target = "<span class='hide target'>".$data['attr']['target']."</span>";	
		}
		$data = get_data();
		return '<p>
					<span class="label">Пользовательская Фавиконка</span> <input type="text" class="width10" name="setting-favicon" value="'.$data['setting-favicon'].'" /> <br />
					'.$target.'
					<span class="pushlabel" style="display:block;">
						<a href="#" class="upload-btn upload-image favicon" id="setting-'.$data['category'].'-'.$data['title'].'">+ Загрузить</a>
					</span>
				</p>';
	}

	///////////////////////////////////////////
	// Favicon Module - Action
	///////////////////////////////////////////
	function themify_favicon_action($data=array()){
		$data = get_data();
		if($data['setting-favicon'] != ""){
			echo "\n\n".'<link href="'.$data['setting-favicon'].'" rel="shortcut icon" /> ';
		}
	}
	add_action('wp_head', 'themify_favicon_action');
	add_action('admin_head', 'themify_favicon_action');
	
	///////////////////////////////////////////
	// Custom Feed URL Module
	///////////////////////////////////////////
	function themify_custom_feed_url($data=array()){
		$data = get_data();
		return '<p><span class="label">Пользовательская RSS Лента</span> <input type="text" class="width10" name="setting-custom_feed_url" value="'.$data['setting-custom_feed_url'].'" /> <br />
					<span class="pushlabel"><small>напр. http://feedburner.com/userid</small></span></p>';
	}
	
	///////////////////////////////////////////
	// Custom Feed URL Module - Action
	///////////////////////////////////////////
	function themify_custom_feed_url_action($data=array()){
		$data = get_data();
		if($data['setting-custom_feed_url'] != ""){
			echo "\n\n".'<meta name="description" content="'.$data['setting-custom_feed_url'].'" /> ';
		}
	}
	add_action('wp-admin','themify_custom_feed_url_action');
	
	///////////////////////////////////////////
	// Meta Description Module
	///////////////////////////////////////////
	function themify_meta_description($data=array()){
		$data = get_data();
		return '<p><textarea type="text" name="setting-meta_description" class="widthfull" rows="4">'.$data['setting-meta_description'].'</textarea></p>';	
	}
	
	///////////////////////////////////////////
	// Meta Description Module - Action
	///////////////////////////////////////////
	function themify_meta_description_action($data=array()){
		$data = get_data();
		if($data['setting-meta_description'] != ""){
			echo "\n\n".'<meta name="description" content="'.$data['setting-meta_description'].'" /> ';
		}
	}
	add_action('wp-admin','themify_meta_description_action');
	
	///////////////////////////////////////////
	// Header HTML Module
	///////////////////////////////////////////
	function themify_header_html($data=array()){
		$data = get_data();
		return '<p>Следующий код будет добавлен в &lt;head&gt; тег.</p>
					<p><textarea class="widthfull" rows="10" name="setting-header_html">'.$data['setting-header_html'].'</textarea><br />
					<small>Полезно, если вам нужно добавить дополнительные скрипты, такие как CSS или JS.</small></p>';	
	}
	
	///////////////////////////////////////////
	// Header HTML Module - Action
	///////////////////////////////////////////
	function themify_header_html_action($data=array()){
		$data = get_data();
		echo "\n\n".$data['setting-header_html'];
	}
	add_action('wp_head','themify_header_html_action');
	
	///////////////////////////////////////////
	// Footer HTML Module
	///////////////////////////////////////////
	function themify_footer_html($data=array()){
		$data = get_data();
		return '<p>Следующий код будет добавлен в подвал до закрытия &lt;/body&gt; тега.</p>
					<p><textarea type="text" class="widthfull" rows="10" name="setting-footer_html">'.$data['setting-footer_html'].'</textarea><br />
					<small>Полезно, если вам нужен Javascript или код отслеживания.</small></p>';
	}
	
	///////////////////////////////////////////
	// Footer HTML Module - Action
	///////////////////////////////////////////
	function themify_footer_html_action($data=array()){
		$data = get_data();
		echo "\n\n".$data['setting-footer_html'];
	}
	add_action('wp_footer','themify_footer_html_action');
	
		
	///////////////////////////////////////////
	// Custom CSS Module
	///////////////////////////////////////////
	function themify_custom_css($data=array()){
		$data = get_data();
		return '<p><textarea class="widthfull" rows="35" name="setting-custom_css">'.$data['setting-custom_css'].'</textarea><br /></p>';	
	}
	///////////////////////////////////////////
	// Custom CSS Module - Action
	///////////////////////////////////////////
	function themify_custom_css_action($data=array()){
		$data = get_data();
		echo "\n\n<!-- custom css -->\n\n<style type='text/css'>".$data['setting-custom_css']."</style>";
	}
	add_action('wp_head','themify_custom_css_action');
	
	///////////////////////////////////////////
	// Search Settings Module
	///////////////////////////////////////////
	function themify_search_settings($data=array()){
		$data = get_data();
		if($data['setting']['search_settings_exclude']){
			$checked = "checked='checked'";	
		}
		return '<p><span class="label">Поиск в ID Категории </span>
					   <input type="text" class="width6" name="setting-search_settings" value="'.$data['setting-search_settings'].'" />
					</p>
					<p>
						<span class="pushlabel"><small>Используйте знак "минус" (-), чтобы исключить категории.</small></span><br />
						<span class="pushlabel"><small>Например: (1,4,-7) = искать только в Категориях 1 и 4, а также исключить Категорию 7.</small></span>
					</p>
					<p><span class="pushlabel"><input type="checkbox" name="setting-search_settings_exclude" '.$checked.'/> Исключить Страницы в результатах поиска</span></p>';	
	}
	
	///////////////////////////////////////////
	// Search Settings Module - Action 
	///////////////////////////////////////////
	function themify_search_settings_action($query){
		$data = get_data();
		if($query->is_search){
			if($data['setting-search_settings'] != ""){
				$query->set('cat',$data['setting-search_settings']);
			}
			if($data['setting-search_settings_exclude']){
				$query->set('post_type','post');
			} 
		}
		return $query;
	}
	add_filter('pre_get_posts','themify_search_settings_action');
	
	///////////////////////////////////////////
	// RSS Feed Settings Module
	///////////////////////////////////////////
	function themify_feed_settings($data=array()){
		$data = get_data();
		if(themify_check('setting-exclude_img_rss')){
			$checked_use = "checked='checked'";
		}
		return '<p><span class="label">Категория потока</span> <input type="text" class="width6" name="setting-feed_settings" value="'.$data['setting-feed_settings'].'" /></p>
				<p>
					<span class="pushlabel"><small>Используйте знак "минус" (-), чтобы исключить категории.</small></span><br />
					<span class="pushlabel"><small>Напримерe: (2,-9) = включают только 2 категорию в потоке и исключить категорию 9.</small></span>
				</p>
				<p><span class="label">Изображение записи в RSS</span> <input type="checkbox" name="setting-exclude_img_rss" '.$checked_use.'/> Исключить изображения записей в RSS потоке</p>
				<p>
					<span class="pushlabel"><small>Отметьте это, чтобы исключить изображения записей в RSS потоке</small></span>
				</p>
					';	
	}
	
	///////////////////////////////////////////
	// RSS Feed Settings Module - Action
	///////////////////////////////////////////
	function themify_feed_settings_action($query){
		$data = get_data();
		if($query->is_feed){
			if(isset($data['setting-feed_settings'])){
				$query->set('cat',$data['setting-feed_settings']);	
			}
		}
	}
	add_filter('pre_get_posts','themify_feed_settings_action');

	///////////////////////////////////////
	// Filter RSS Feed to include post image - Action
	///////////////////////////////////////
	if($data['setting-exclude_img_rss'] == ""){
		add_filter('the_content', 'themify_custom_fields_for_feeds');
	
		function themify_custom_fields_for_feeds( $content ) {
	
			global $post, $id, $themify_check;
			if(!is_feed() || $themify_check == true){
				return $content;
			}
	
			if(themify_check('post_image')) {
				$content .= "<p><img src='".themify_get('post_image')."'></p>";
			}
			$themify_check = false;
			return $content;
		}
	}
	
	///////////////////////////////////////////
	// Img Version / Settings
	///////////////////////////////////////////
	function themify_img_settings($data=array()){
		if(themify_check('setting-img_settings_use')){
			$checked_use = "checked='checked'";
		}
		if(themify_check('setting-img_settings_legacy')){
			$checked_legacy = "checked='checked'";
		}
		return '<div class="module">
					<div class="label">img.php</div> 
					<div class="row">
						<input type="checkbox" name="setting-img_settings_use" '.$checked_use.'/> Отключить img.php, чтобы генерировать динамические изображения<br>
						<small>(будут использоваться оригинальные исходные изображения)</small>
					</div>
				</div>';
	}
	
	///////////////////////////////////////////
	// Shortcode Settings
	///////////////////////////////////////////
	function themify_shortcode_settings($data=array()){
		$data = get_data();
		if($data['setting-google_map_script']){
			$shortcode_checked = "checked='checked'";	
		}
		$output .= '<p><span class="label">Google Карта</span><input type="checkbox" name="setting-google_map_script" '.$shortcode_checked.' /> Исключить Google Карту API <br> <small>(отметьте это, если вы не используете карту <a href="http://themify.me/docs/shortcodes" target="_blank">короткий код</a>, проверьте это, чтобы оптимизировать Вашу тему)</small></p>';	
		$shortcode_checked = "";
		if($data['setting-video_player_script']){
			$shortcode_checked = "checked='checked'";	
		}
		$output .= '<p><span class="label">Видеоплеер</span><input type="checkbox" name="setting-video_player_script" '.$shortcode_checked.' /> Исключить Видеоплеер Javascript <br> <small>(отметьте это, если вы не используете видеоплеер <a href="http://themify.me/docs/shortcodes" target="_blank">короткий код</a>, проверьте это, чтобы оптимизировать Вашу тему)</small></p>';	
		$shortcode_checked = "";
		if($data['setting-slider_script']){
			$shortcode_checked = "checked='checked'";	
		}
		$output .= '<p><span class="label">Слайдер</span><input type="checkbox" name="setting-slider_script" '.$shortcode_checked.' /> Исключить Слайдер Javascript <br> <small>(отметьте это, если вы не используете слайдер <a href="http://themify.me/docs/shortcodes" target="_blank">короткий код</a>, проверьте это, чтобы оптимизировать Вашу тему)</small></p>';	
		$shortcode_checked = "";
		if($data['setting-shortcode_css']){
			$shortcode_checked = "checked='checked'";	
		}
		$output .= '<p><span class="label">Shortcode.css</span><input type="checkbox" name="setting-shortcode_css" '.$shortcode_checked.' /> Исключить shortcodes.css <br> <small>(отметьте это, чтобы исключить shortcodes.css)</small></p>';	
		
		return $output;												 
	}
	
/* 	Styling Modules
/***************************************************************************/	
	
	///////////////////////////////////////////
	// Divider Module
	///////////////////////////////////////////
	function themify_divider($data=array()){
		return '<hr/>';
	}
	
	///////////////////////////////////////////
	// Image Preview Module
	///////////////////////////////////////////
	function themify_image_preview($data=array()){
		global $config;
		$temp = get_data();
		$output = '<div class="preset">';
		if($data['attr']['src'] != ""){
			$img_folders = array(0 => array('_a' => array('src' => $data['attr']['src']))); 	
		} else {
			$img_folders = $config['folders']['_c']['images'];	
		}
		if(is_array($img_folders)){
			if(isset($img_folders['_a']['src'])){
				$folder = $folder['_a']['src'];
				if(is_dir(TEMPLATEPATH.'/'.$folder)){
					if($handle = opendir(TEMPLATEPATH.'/'.$folder)) {
						while (false !== ($file = readdir($handle))) {
							$ext = substr(strrchr($file, '.'), 1);
							if($ext == 'jpg' || $ext == 'gif' || $ext == 'png'){
								$fullpath = get_bloginfo('template_directory')."/".$folder.$file;
								$savedpath = $temp['styling-'.$data['category'].'-'.$data['title'].'-background_image-value-value'];
								if(trim($fullpath) == trim($savedpath)){
									$output .= '<a href="#" title="'.$folder.$file.'"><span title="'.$folder.$file.'"></span>'.themify_get_image('w=50&h=50&src='.$fullpath.'&alt='.$fullpath.'&class=backgroundThumb selected').'</a>';				
								} else {
									$output .= '<a href="#" title="'.$folder.$file.'"><span title="'.$folder.$file.'"></span>'.themify_get_image('w=50&h=50&src='.$fullpath.'&alt='.$fullpath.'&class=backgroundThumb').'</a>';
								}
							}
						}		
						closedir($handle);
					}
				}
			} else {
				foreach($img_folders as $folder){
					$folder = $folder['_a']['src'];
					if(is_dir(TEMPLATEPATH.'/'.$folder)){
						if($handle = opendir(TEMPLATEPATH.'/'.$folder)) {
							while (false !== ($file = readdir($handle))) {
								$ext = substr(strrchr($file, '.'), 1);
								if($ext == 'jpg' || $ext == 'gif' || $ext == 'png'){
									$fullpath = get_bloginfo('template_directory')."/".$folder.$file;
									$savedpath = $temp['styling-'.$data['category'].'-'.$data['title'].'-background_image-value-value'];
									if(trim($fullpath) == trim($savedpath)){
										$output .= '<a href="#" title="'.$folder.$file.'"><span title="'.$folder.$file.'"></span>'.themify_get_image('w=50&h=50&src='.$fullpath.'&alt='.$fullpath.'&class=backgroundThumb selected').'</a>';				
									} else {
										$output .= '<a href="#" title="'.$folder.$file.'"><span title="'.$folder.$file.'"></span>'.themify_get_image('w=50&h=50&src='.$fullpath.'&alt='.$fullpath.'&class=backgroundThumb').'</a>';
									}
								}
							}		
							closedir($handle);
						}
					}
				}
			}
		}
		$output .= '</div>';	
		return $output;
	}
	
	///////////////////////////////////////////
	// Background Image Module
	///////////////////////////////////////////
	function themify_background_image($data=array()){	
		if($data['attr']['target'] != ''){
			$target = "<span class='hide target'>".$data['attr']['target']."</span>";	
		}
		$data['value'] = $data['value']['value'];
		$none_checked = "";
		if($data['value']['none']){
			$none_checked = "checked='checked'";
		}
		$output .= '<p class="background_image">
						<span class="label">Фоновое изображение</span> 
						'.$target.'
						<input type="text" name="styling-'.$data['category'].'-'.$data['title'].'-background_image-value-value" class="width8 upload-file" id="styling-'.$data['category'].'-'.$data['title'].'-background_image" value="'.$data['value']['value'].'" /> 
						<input type="checkbox" name="styling-'.$data['category'].'-'.$data['title'].'-background_image-value-none" '.$none_checked.' /> Ничего<br />
							
						<span class="pushlabel" style="display:block;">
							<a href="#" class="upload-btn upload-image" id="styling-'.$data['category'].'-'.$data['title'].'">+ Загрузить</a>
						</span>
					</p>';		
		return $output;
	}
	
	///////////////////////////////////////////
	// Background Color Module
	///////////////////////////////////////////
	function themify_background_color($data=array()){
		$data['value'] = $data['value']['value'];
		if($data['value']['transparent']){
			$output = '<p class="background_color">
						<span class="label">Цвет Фона</span> 
						<span class="colorSelect" style=""><span></span></span> <input type="text" disabled name="styling-'.$data['category'].'-'.$data['title'].'-background_color-value-value" class="width4" /> 
						<input type="checkbox" checked="checked" name="styling-'.$data['category'].'-'.$data['title'].'-background_color-value-transparent" class="colorTransparent" /> Прозрачный
					</p>';
		} else {
			$output = '<p>
						<span class="label">Цвет Фона</span> 
						<span class="colorSelect "style="background-color:#'.$data['value']['value'].';"><span></span></span> <input type="text" name="styling-'.$data['category'].'-'.$data['title'].'-background_color-value-value" value="'.$data['value']['value'].'" class="colorSelectInput width4" /> 
						<input type="checkbox" name="styling-'.$data['category'].'-'.$data['title'].'-background_color-value-transparent" class="colorTransparent" /> Прозрачный
					</p>';
		}
		return $output;
	}
	
	///////////////////////////////////////////
	// Background Repeat Module
	///////////////////////////////////////////
	function themify_background_repeat($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('repeat', 'repeat-x','repeat-y','no-repeat');
		$output = '<p><span class="label">Фоновое повторение</span>
					<select name="styling-'.$data['category'].'-'.$data['title'].'-background_repeat-value-value"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['value']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';
			}
		}
		$output .=	'</select></p>';	
		return $output;
	}
	
	///////////////////////////////////////////
	// Background Position Module
	///////////////////////////////////////////
	function themify_background_position($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('left','center','right');
		$output = '	<p><span class="label">Фоновая позиция</span> 
					<select class="background_position positionX"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['x']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select>
					<span class="value" style="display:none;">
						<input type="text" name="styling-'.$data['category'].'-'.$data['title'].'-background_position-value-x" value="'.$data['value']['x'].'" class="valueX">
					</span>';
		$options = array('top','center','bottom');
		$output .= '<select class="background_position positionY"><option> </option>';
		
		foreach($options as $option){
			if($option == $data['value']['y']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select>
					<span class="value" style="display:none;">
						<input type="text" name="styling-'.$data['category'].'-'.$data['title'].'-background_position-value-y" value="'.$data['value']['y'].'" class="valueY">
					</span>
					</p>';
					
		return $output;
	}
	
	///////////////////////////////////////////
	// Font Family Module
	///////////////////////////////////////////
	function themify_font_family($data=array()){
		$data['value'] = $data['value']['value'];
		$fonts = array("Arial, Helvetica, sans-serif",
						"Verdana, Geneva, sans-serif",
						"Georgia, \"Times New Roman\", Timers, serif",
						"\"Times New Roman\", Times, serif",
						"Tahoma, Geneva, sans-serif",
						"\"Trebuchet MS\", Arial, Helvetica, sans-serif",
						"Palatino, \"Palatino Linotype\", \"Book Antiqua\", serif",
						"\"Lucida Sans Unicode\", \"Lucida Grande\", sans-serif");
		$output .= '<p><span class="label">Семейство шрифтов</span> 
					<select class="fontFamily" name="styling-'.$data['category'].'-'.$data['title'].'-font_family-value-value"><option> </option>';
		foreach($fonts as $font){
			if($font == $data['value']['value']){
				$check = true;
				$output .= '<option value=\''.$font.'\' selected="selected">'.$font.'</option>';
			} else {
				$output .= '<option value=\''.$font.'\'>'.$font.'</option>';	
			}
		}
		$output .= '</select></p>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Font Size Module
	///////////////////////////////////////////
	function themify_font_size($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('px','em','%');
		$output .= '<p><span class="label">Размер шрифта</span> 
					<input type="text" class="width2 valid_num" name="styling-'.$data['category'].'-'.$data['title'].'-font_size-value-value" value="'.$data['value']['value'].'" />
					<select name="styling-'.$data['category'].'-'.$data['title'].'-font_size-value-unit"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['unit']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';
			}
		}
		$output .=	'</select></p>';	
		return $output;
	}
	
	///////////////////////////////////////////
	// Font Weight Module
	///////////////////////////////////////////
	function themify_font_weight($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('normal','bold');
		$output = '<p><span class="label">Насыщенность шрифта</span> <select  name="styling-'.$data['category'].'-'.$data['title'].'-font_weight-value-value"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['value']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select></p>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Font Style Module
	///////////////////////////////////////////
	function themify_font_style($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('normal','italic');
		$output = '<p><span class="label">Стиль шрифта</span> <select name="styling-'.$data['category'].'-'.$data['title'].'-font_style-value-value"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['value']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select></p>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Font Variant Module
	///////////////////////////////////////////
	function themify_font_variant($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('normal','small-caps');
		$output = '<p><span class="label">Разновидность шрифта</span> <select name="styling-'.$data['category'].'-'.$data['title'].'-font_variant-value-value"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['value']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select></p>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Line Height Module
	///////////////////////////////////////////
	function themify_line_height($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('px','em','%');
		$output = '	<p><span class="label">Высота строки</span>
					<input type="text" class="width2 valid_num"  name="styling-'.$data['category'].'-'.$data['title'].'-line_height-value-value" value="'.$data['value']['value'].'" /><select name="styling-'.$data['category'].'-'.$data['title'].'-line_height-value-unit"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['unit']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select></p>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Text Transform Module
	///////////////////////////////////////////
	function themify_text_transform($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('capitalize','uppercase','lowercase','none');
		$output = '	<p><span class="label">Преобразовать текст</span> <select name="styling-'.$data['category'].'-'.$data['title'].'-text_transform-value-value"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['value']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select></p>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Text Decoration Module
	///////////////////////////////////////////
	function themify_text_decoration($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('underline','overline','line-through','none');
		$output = '	<p><span class="label">Оформления текста</span> <select name="styling-'.$data['category'].'-'.$data['title'].'-text_decoration-value-value"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['value']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select></p>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Font Color Module
	///////////////////////////////////////////
	function themify_color($data=array()){
		$data['value'] = $data['value']['value'];
		return '<p><span class="label">Цвет</span> <span class="colorSelect" style="background:#'.$data['value']['value'].';"><span></span></span> <input type="text" class="colorSelectInput width4" value="'.$data['value']['value'].'" name="styling-'.$data['category'].'-'.$data['title'].'-color-value-value" /></p>';
	}
	
	///////////////////////////////////////////
	// Padding Module
	///////////////////////////////////////////
	function themify_padding($data=array()){
		$data['value'] = $data['value']['value'];
		if($data['value']['checkbox']){
			$checked = "checked='checked'";
			$individuals = "style='display:none;'";	
		} else {
			$same = "style='display:none;'";
		}
		$output .= '<div>
						<p>
							<span class="label">Набивка</span>
							<span class="same" '.$same.'>
								<input type="text" class="width2 valid_num" name="styling-'.$data['category'].'-'.$data['title'].'-padding-value-same" value="'.$data['value']['same'].'" /> <small>px</small>
							</span>
							<span class="individuals" '.$individuals.'>
								<input type="text" class="width2 valid_num" name="styling-'.$data['category'].'-'.$data['title'].'-padding-value-top" value="'.$data['value']['top'].'" /> верхний 
								<input type="text" class="width2 valid_num" name="styling-'.$data['category'].'-'.$data['title'].'-padding-value-right" value="'.$data['value']['right'].'" /> правый 
								<input type="text" class="width2 valid_num"  name="styling-'.$data['category'].'-'.$data['title'].'-padding-value-bottom" value="'.$data['value']['bottom'].'"/> нижний 
								<input type="text" class="width2 valid_num" name="styling-'.$data['category'].'-'.$data['title'].'-padding-value-left" value="'.$data['value']['left'].'" /> левый <small>(px)</small>
							</span>
						</p>
						<p>
							<span class="pushlabel" style="display:block;">
								<input type="checkbox" name="styling-'.$data['category'].'-'.$data['title'].'-padding-value-checkbox" class="padding-switch" '.$checked.' /> То же самое для всех
							</span>
						</p>
					</div>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Margin Module
	///////////////////////////////////////////
	function themify_margin($data=array()){
		$data['value'] = $data['value']['value'];
		if($data['value']['checkbox']){
			$checked = "checked='checked'";
			$individuals = "style='display:none;'";	
		} else {
			$same = "style='display:none;'";
		}
		$output .= '<div>
						<p>
							<span class="label">Край</span>';
		$output .= '<span class="same" '.$same.'>
						<input type="text" class="width2 valid_num" name="styling-'.$data['category'].'-'.$data['title'].'-margin-value-same" value="'.$data['value']['same'].'" /> <small>px</small>
					</span>
					<span class="individuals" '.$individuals.'>
						<input type="text" class="width2 valid_num" name="styling-'.$data['category'].'-'.$data['title'].'-margin-value-top" value="'.$data['value']['top'].'" /> верхний  
						<input type="text" class="width2 valid_num" name="styling-'.$data['category'].'-'.$data['title'].'-margin-value-right" value="'.$data['value']['right'].'" /> правый 
						<input type="text" class="width2 valid_num"  name="styling-'.$data['category'].'-'.$data['title'].'-margin-value-bottom" value="'.$data['value']['bottom'].'"/> нижний 
						<input type="text" class="width2 valid_num" name="styling-'.$data['category'].'-'.$data['title'].'-margin-value-left" value="'.$data['value']['left'].'" /> левый <small>(px)</small>
					</span>
				</p>
				<p>
					<span class="pushlabel" style="display:block;">
						<input type="checkbox" name="styling-'.$data['category'].'-'.$data['title'].'-margin-value-checkbox" '.$checked.' class="margin-switch" /> То же самое для всех
					</span>
				</p>
			</div>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Height Module
	///////////////////////////////////////////
	function themify_height($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('px','em','%');
		$output = '	<p><span class="label">Высота</span> 
					<input type="text" class="width2 valid_num" value="'.$data['value']['value'].'" name="styling-'.$data['category'].'-'.$data['title'].'-height-value-value" />  
					<select name="styling-'.$data['category'].'-'.$data['title'].'-height-value-unit"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['unit']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select></p>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Width Module
	///////////////////////////////////////////
	function themify_width($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('px','em','%');
		$output = '	<p><span class="label">Ширина</span> 
					<input type="text" class="width2 valid_num" value="'.$data['value']['value'].'" name="styling-'.$data['category'].'-'.$data['title'].'-width-value-value" />  
					<select name="styling-'.$data['category'].'-'.$data['title'].'-width-value-unit"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['unit']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select></p>';
		return $output;
	}
	
	///////////////////////////////////////////
	// Border Module
	///////////////////////////////////////////
	function themify_border($data=array()){
		$data['value'] = $data['value']['value'];
		if($data['value']['checkbox']){
			$checked = "checked='checked'";
			$individuals = "style='display:none;'";	
		} else {
			$same = "style='display:none;'";
		}
		$options = array('solid','dashed','dotted','double');
		$output = '<div><p>
						<span class="label">Граница</span> 
						<span class="same" '.$same.'>
							<span class="colorSelect" style="background-color:#'.$data['value']['same_color'].'"><span></span></span>  <input type="text" value="'.$data['value']['same_color'].'" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-same_color" class="width4 colorSelectInput" /> 
							<input type="text" class="width2 valid_num" value="'.$data['value']['same'].'" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-same" /> <small>px</small> 
							<select name="styling-'.$data['category'].'-'.$data['title'].'-border-value-same_style"><option> </option>';
							foreach($options as $option){
								if($option == $data['value']['same_style']){
									$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
								} else {
									$output .= '<option value="'.$option.'">'.$option.'</option>';	
								}
							}
		$output .= '		</select>
						</span>
						<span class="individuals" '.$individuals.'>
						<span class="borders">
							<span class="colorSelect" style="background-color:#'.$data['value']['top_color'].';"><span></span></span> <input type="text" value="'.$data['value']['top_color'].'" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-top_color" class="width4 colorSelectInput" /> 
							<input type="text" class="width2 valid_num" value="'.$data['value']['top'].'" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-top" /> <small>px</small>
							<select name="styling-'.$data['category'].'-'.$data['title'].'-border-value-top_style"><option> </option>';
							foreach($options as $option){
								if($option == $data['value']['top_style']){
									$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
								} else {
									$output .= '<option value="'.$option.'">'.$option.'</option>';	
								}
							}
		$output .= '		</select> верхний
						</span>
						<span class="pushlabel borders" style="display:block;">
							<span class="colorSelect" style="background-color:#'.$data['value']['right_color'].';"><span></span></span> <input type="text" value="'.$data['value']['right_color'].'" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-right_color" class="width4 colorSelectInput" /> 
							<input type="text" class="width2 valid_num" value="'.$data['value']['right'].'" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-right" /> <small>px</small>
							<select name="styling-'.$data['category'].'-'.$data['title'].'-border-value-right_style"><option> </option>';
							foreach($options as $option){
								if($option == $data['value']['right_style']){
									$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
								} else {
									$output .= '<option value="'.$option.'">'.$option.'</option>';	
								}
							}
		$output .= '		</select> правый
						</span>
						<span class="pushlabel borders" style="display:block;">
							<span class="colorSelect" style="background-color:#'.$data['value']['bottom_color'].';"><span></span></span> <input type="text" value="'.$data['value']['bottom_color'].'" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-bottom_color" class="width4 colorSelectInput" /> 
							<input type="text" class="width2 valid_num" value="'.$data['value']['bottom'].'" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-bottom" /> <small>px</small>
							<select name="styling-'.$data['category'].'-'.$data['title'].'-border-value-bottom_style"><option> </option>';
							foreach($options as $option){
								if($option == $data['value']['bottom_style']){
									$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
								} else {
									$output .= '<option value="'.$option.'">'.$option.'</option>';	
								}
							}
		$output .= '		</select> нижний
						</span>
						<span class="pushlabel borders" style="display:block;">
							<span class="colorSelect" style="background-color:#'.$data['value']['left_color'].';"><span></span></span> <input type="text" value="'.$data['value']['left_color'].'" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-left_color" class="width4 colorSelectInput" /> 
							<input type="text" class="width2 valid_num" value="'.$data['value']['left'].'" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-left" /> <small>px</small>
							<select name="styling-'.$data['category'].'-'.$data['title'].'-border-value-left_style"><option> </option>';
							foreach($options as $option){
								if($option == $data['value']['left_style']){
									$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
								} else {
									$output .= '<option value="'.$option.'">'.$option.'</option>';	
								}
							}
		$output .= '		</select> левый
						</span>
					</span>
					</p>
					<p>
						<span class="pushlabel" style="display:block;">
							<input type="checkbox" class="border-switch" name="styling-'.$data['category'].'-'.$data['title'].'-border-value-checkbox" '.$checked.' /> То же самое для всех
						</span>
					</p>
				</div>';				
		return $output;
	}
	
	///////////////////////////////////////////
	// Position Module
	///////////////////////////////////////////
	function themify_position($data=array()){
		$data['value'] = $data['value']['value'];
		$options = array('static','fixed','relative','absolute');
		$options_x = array('top','bottom');
		$options_y = array('left','right');
		if($data['value']['value'] != 'fixed' && $data['value']['value'] != 'absolute'){
			$display = "style='display:none;'";	
		}
		$output = '	<p><span class="label">Положение</span>
					<select name="styling-'.$data['category'].'-'.$data['title'].'-position-value-value" class="select_position"><option> </option>';
		foreach($options as $option){
			if($option == $data['value']['value']){
				$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
			} else {
				$output .= '<option value="'.$option.'">'.$option.'</option>';	
			}
		}
		$output .= '</select></p>
					<p class="position_display" '.$display.'>
						<span class="pushlabel" style="display:block;">
						<select name="styling-'.$data['category'].'-'.$data['title'].'-position-value-x"><option> </option>';
						foreach($options_x as $option){
							if($option == $data['value']['x']){
								$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
							} else {
								$output .= '<option value="'.$option.'">'.$option.'</option>';	
							}
						}	
		$output .=	'	</select>
						<input type="text" class="width2 valid_num" value="'.$data['value']['x_value'].'" name="styling-'.$data['category'].'-'.$data['title'].'-position-value-x_value" /> <small>px</small> 
						</span>
						<span class="pushlabel" >
						<select name="styling-'.$data['category'].'-'.$data['title'].'-position-value-y"><option> </option>';
						foreach($options_y as $option){
							if($option == $data['value']['y']){
								$output .= '<option value="'.$option.'" selected="selected">'.$option.'</option>';	
							} else {
								$output .= '<option value="'.$option.'">'.$option.'</option>';	
							}
						}	
		$output .=	'	</select>
						<input type="text" class="width2 valid_num" value="'.$data['value']['y_value'].'" name="styling-'.$data['category'].'-'.$data['title'].'-position-value-y_value" /> <small>px</small> 
						</span>
					</p>';
		return $output;	
	}

?>